In [221]:
#T.BRADFORD
#July 2021
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json
from datetime import datetime
from census import Census

# Census API Key
from config import api_key

In [222]:
# Run Census Search to retrieve population data
url_2019_county ="https://api.census.gov/data/2019/pep/population?get=NAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2019_county)
response_json = response.json()

In [223]:
#Create and rename Dataframe
census_2019_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"NAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"COUNTY_ID"})
census_2019_county["POPULATION"].astype(int)

#string split
census_2019_county[['COUNTY_NAME', 'STATE']] = census_2019_county['COUNTY, STATE'].str.split(',', 1, expand=True)
census_2019_county[['DATE', 'Trash']] = census_2019_county['DATE'].str.split(' ', 1, expand=True)

#convert Date to a datetime object
census_2019_county['DATE'] = pd.to_datetime(census_2019_county['DATE'])
#reduced dataframe
census_2019_county = census_2019_county[["COUNTY_ID","COUNTY_NAME","STATE","POPULATION","DATE"]]

census_2019_county

     COUNTY_ID       COUNTY_NAME        STATE POPULATION       DATE
0          023    Hidalgo County   New Mexico       4198 2019-07-01
1          017     Hudson County   New Jersey     672391 2019-07-01
2          019  Hunterdon County   New Jersey     124371 2019-07-01
3          027     Morris County   New Jersey     491845 2019-07-01
4          031   McKinley County   New Mexico      71367 2019-07-01
...        ...               ...          ...        ...        ...
3215       047   Okanogan County   Washington      42243 2019-07-01
3216       037   Kittitas County   Washington      47935 2019-07-01
3217       005     Benton County   Washington     204390 2019-07-01
3218       011      Clark County   Washington     488241 2019-07-01
3219       177     Warren County    Tennessee      41277 2019-07-01

[3220 rows x 5 columns]

In [224]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2019_county.to_csv("census_2019_county.csv", encoding="utf-8", index=False)

In [225]:
# Run Census Search to retrieve population data
url_2018_county ="https://api.census.gov/data/2018/pep/population?get=GEONAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2018_county)
response_json = response.json()

In [226]:
#Create and rename Dataframe
census_2018_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"COUNTY_ID"})
census_2018_county["POPULATION"].astype(int)

#string split
census_2018_county[['COUNTY_NAME', 'STATE']] = census_2018_county['COUNTY, STATE'].str.split(',', 1, expand=True)
census_2018_county[['DATE', 'Trash']] = census_2018_county['DATE'].str.split(' ', 1, expand=True)

#convert Date to a datetime object
census_2018_county['DATE'] = pd.to_datetime(census_2018_county['DATE'])

#reduced dataframe
census_2018_county = census_2018_county[["COUNTY_ID","COUNTY_NAME","STATE","POPULATION","DATE"]]

census_2018_county

     COUNTY_ID          COUNTY_NAME         STATE POPULATION       DATE
0          001       Autauga County       Alabama      55601 2018-07-01
1          003       Baldwin County       Alabama     218022 2018-07-01
2          005       Barbour County       Alabama      24881 2018-07-01
3          007          Bibb County       Alabama      22400 2018-07-01
4          009        Blount County       Alabama      57840 2018-07-01
...        ...                  ...           ...        ...        ...
3215       145  Vega Baja Municipio   Puerto Rico      50185 2018-07-01
3216       147    Vieques Municipio   Puerto Rico       8364 2018-07-01
3217       149   Villalba Municipio   Puerto Rico      21476 2018-07-01
3218       151    Yabucoa Municipio   Puerto Rico      32158 2018-07-01
3219       153      Yauco Municipio   Puerto Rico      33860 2018-07-01

[3220 rows x 5 columns]

In [227]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2018_county.to_csv("census_2018_county.csv", encoding="utf-8", index=False)

In [228]:
# Run Census Search to retrieve population data
url_2017_county ="https://api.census.gov/data/2017/pep/population?get=GEONAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2017_county)
response_json = response.json()

In [229]:
#Create and rename Dataframe
census_2017_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"COUNTY_ID"})
census_2017_county["POPULATION"].astype(int)

#string split
census_2017_county[['COUNTY_NAME', 'STATE']] = census_2017_county['COUNTY, STATE'].str.split(',', 1, expand=True)
census_2017_county[['DATE', 'Trash']] = census_2017_county['DATE'].str.split(' ', 1, expand=True)

#convert Date to a datetime object
census_2017_county['DATE'] = pd.to_datetime(census_2017_county['DATE'])

#reduced dataframe
census_2017_county = census_2017_county[["COUNTY_ID","COUNTY_NAME","STATE","POPULATION","DATE"]]

census_2017_county

,COUNTY_ID,COUNTY_NAME,STATE,POPULATION,DATE
0,035,Conecuh County,Alabama,12469,2017-07-01
1,037,Coosa County,Alabama,10754,2017-07-01
2,039,Covington County,Alabama,37092,2017-07-01
3,041,Crenshaw County,Alabama,13871,2017-07-01
4,043,Cullman County,Alabama,82755,2017-07-01
...,...,...,...,...,...
3215,099,Moca Municipio,Puerto Rico Commonwealth,36328,2017-07-01
3216,101,Morovis Municipio,Puerto Rico Commonwealth,31092,2017-07-01
3217,103,Naguabo Municipio,Puerto Rico Commonwealth,26177,2017-07-01
3218,105,Naranjito Municipio,Puerto Rico Commonwealth,28306,2017-07-01
3219,107,Orocovis Municipio,Puerto Rico Commonwealth,21109,2017-07-01

In [230]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2017_county.to_csv("census_2017_county.csv", encoding="utf-8", index=False)

In [231]:
# Run Census Search to retrieve population data
url_2016_county ="https://api.census.gov/data/2016/pep/population?get=GEONAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2016_county)
response_json = response.json()

In [232]:
#Create and rename Dataframe
census_2016_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"COUNTY_ID"})
census_2016_county["POPULATION"].astype(int)

#string split
census_2016_county[['COUNTY_NAME', 'STATE']] = census_2016_county['COUNTY, STATE'].str.split(',', 1, expand=True)
census_2016_county[['DATE', 'Trash']] = census_2016_county['DATE'].str.split(' ', 1, expand=True)

#convert Date to a datetime object
census_2016_county['DATE'] = pd.to_datetime(census_2016_county['DATE'])

#reduced dataframe
census_2016_county = census_2016_county[["COUNTY_ID","COUNTY_NAME","STATE","POPULATION","DATE"]]
census_2016_county

     COUNTY_ID           COUNTY_NAME      STATE POPULATION       DATE
0          003        Baldwin County    Alabama     208563 2016-07-01
1          005        Barbour County    Alabama      25965 2016-07-01
2          007           Bibb County    Alabama      22643 2016-07-01
3          009         Blount County    Alabama      57704 2016-07-01
4          011        Bullock County    Alabama      10362 2016-07-01
...        ...                   ...        ...        ...        ...
3215       141        Patrick County   Virginia      17923 2016-07-01
3216       143   Pittsylvania County   Virginia      61687 2016-07-01
3217       145       Powhatan County   Virginia      28443 2016-07-01
3218       147  Prince Edward County   Virginia      23142 2016-07-01
3219       149  Prince George County   Virginia      37845 2016-07-01

[3220 rows x 5 columns]

In [233]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2016_county.to_csv("census_2016_county.csv", encoding="utf-8", index=False)