In [15]:
#T.BRADFORD
#July 2021
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json
from census import Census

# Census API Key
from config import api_key

In [16]:
# Run Census Search to retrieve population data
url_2019_county ="https://api.census.gov/data/2019/pep/population?get=NAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2019_county)
response_json = response.json()

In [17]:
#Create and rename Dataframe
census_2019_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"NAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"County Code"})
census_2019_county["POPULATION"].astype(int)
census_2019_county

,"COUNTY, STATE",POPULATION,DATE,State Code,County Code
0,"Hidalgo County, New Mexico",4198,7/1/2019 population estimate,35,023
1,"Hudson County, New Jersey",672391,7/1/2019 population estimate,34,017
2,"Hunterdon County, New Jersey",124371,7/1/2019 population estimate,34,019
3,"Morris County, New Jersey",491845,7/1/2019 population estimate,34,027
4,"McKinley County, New Mexico",71367,7/1/2019 population estimate,35,031
...,...,...,...,...,...
3215,"Okanogan County, Washington",42243,7/1/2019 population estimate,53,047
3216,"Kittitas County, Washington",47935,7/1/2019 population estimate,53,037
3217,"Benton County, Washington",204390,7/1/2019 population estimate,53,005
3218,"Clark County, Washington",488241,7/1/2019 population estimate,53,011
3219,"Warren County, Tennessee",41277,7/1/2019 population estimate,47,177

In [ ]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2019_county.to_csv("census_2019_county.csv", encoding="utf-8", index=False)

In [24]:
# Run Census Search to retrieve population data
url_2018_county ="https://api.census.gov/data/2018/pep/population?get=GEONAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2018_county)
response_json = response.json()

In [26]:
census_2018_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"County Code"})
census_2018_county["POPULATION"].astype(int)
census_2018_county

,"COUNTY, STATE",POPULATION,DATE,State Code,County Code
0,"Autauga County, Alabama",55601,7/1/2018 population estimate,01,001
1,"Baldwin County, Alabama",218022,7/1/2018 population estimate,01,003
2,"Barbour County, Alabama",24881,7/1/2018 population estimate,01,005
3,"Bibb County, Alabama",22400,7/1/2018 population estimate,01,007
4,"Blount County, Alabama",57840,7/1/2018 population estimate,01,009
...,...,...,...,...,...
3215,"Vega Baja Municipio, Puerto Rico",50185,7/1/2018 population estimate,72,145
3216,"Vieques Municipio, Puerto Rico",8364,7/1/2018 population estimate,72,147
3217,"Villalba Municipio, Puerto Rico",21476,7/1/2018 population estimate,72,149
3218,"Yabucoa Municipio, Puerto Rico",32158,7/1/2018 population estimate,72,151
3219,"Yauco Municipio, Puerto Rico",33860,7/1/2018 population estimate,72,153

In [19]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2018_county.to_csv("census_2018_county.csv", encoding="utf-8", index=False)

In [20]:
url_2017_county ="https://api.census.gov/data/2017/pep/population?get=GEONAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2017_county)
response_json = response.json()

In [27]:
census_2017_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"County Code"})
census_2017_county["POPULATION"].astype(int)
census_2017_county

,"COUNTY, STATE",POPULATION,DATE,State Code,County Code
0,"Autauga County, Alabama",55601,7/1/2018 population estimate,01,001
1,"Baldwin County, Alabama",218022,7/1/2018 population estimate,01,003
2,"Barbour County, Alabama",24881,7/1/2018 population estimate,01,005
3,"Bibb County, Alabama",22400,7/1/2018 population estimate,01,007
4,"Blount County, Alabama",57840,7/1/2018 population estimate,01,009
...,...,...,...,...,...
3215,"Vega Baja Municipio, Puerto Rico",50185,7/1/2018 population estimate,72,145
3216,"Vieques Municipio, Puerto Rico",8364,7/1/2018 population estimate,72,147
3217,"Villalba Municipio, Puerto Rico",21476,7/1/2018 population estimate,72,149
3218,"Yabucoa Municipio, Puerto Rico",32158,7/1/2018 population estimate,72,151
3219,"Yauco Municipio, Puerto Rico",33860,7/1/2018 population estimate,72,153

In [28]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2017_county.to_csv("census_2017_county.csv", encoding="utf-8", index=False)

In [22]:
url_2016_county ="https://api.census.gov/data/2016/pep/population?get=GEONAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2016_county)
response_json = response.json()

In [29]:
census_2016_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"County Code"})
census_2016_county["POPULATION"].astype(int)
census_2016_county

,"COUNTY, STATE",POPULATION,DATE,State Code,County Code
0,"Autauga County, Alabama",55601,7/1/2018 population estimate,01,001
1,"Baldwin County, Alabama",218022,7/1/2018 population estimate,01,003
2,"Barbour County, Alabama",24881,7/1/2018 population estimate,01,005
3,"Bibb County, Alabama",22400,7/1/2018 population estimate,01,007
4,"Blount County, Alabama",57840,7/1/2018 population estimate,01,009
...,...,...,...,...,...
3215,"Vega Baja Municipio, Puerto Rico",50185,7/1/2018 population estimate,72,145
3216,"Vieques Municipio, Puerto Rico",8364,7/1/2018 population estimate,72,147
3217,"Villalba Municipio, Puerto Rico",21476,7/1/2018 population estimate,72,149
3218,"Yabucoa Municipio, Puerto Rico",32158,7/1/2018 population estimate,72,151
3219,"Yauco Municipio, Puerto Rico",33860,7/1/2018 population estimate,72,153

In [30]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2016_county.to_csv("census_2016_county.csv", encoding="utf-8", index=False)