In [28]:
#T.BRADFORD
#July 2021
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json
from datetime import datetime
from census import Census

# Census API Key
from config import api_key

In [29]:
# Run Census Search to retrieve population data
url_2019_county ="https://api.census.gov/data/2019/pep/population?get=NAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2019_county)
response_json = response.json()

In [30]:
#Create and rename Dataframe
census_2019_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"NAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"County Code"})
census_2019_county["POPULATION"].astype(int)

#string split
census_2019_county[['COUNTY', 'STATE']] = census_2019_county['COUNTY, STATE'].str.split(',', 1, expand=True)
census_2019_county[['DATE', 'Trash']] = census_2019_county['DATE'].str.split(' ', 1, expand=True)

#convert Date to a datetime object
census_2019_county['DATE'] = pd.to_datetime(census_2019_county['DATE'])
#reduced dataframe
census_2019_county = census_2019_county[["COUNTY","STATE","POPULATION","DATE"]]

census_2019_county

                COUNTY        STATE POPULATION       DATE
0       Hidalgo County   New Mexico       4198 2019-07-01
1        Hudson County   New Jersey     672391 2019-07-01
2     Hunterdon County   New Jersey     124371 2019-07-01
3        Morris County   New Jersey     491845 2019-07-01
4      McKinley County   New Mexico      71367 2019-07-01
...                ...          ...        ...        ...
3215   Okanogan County   Washington      42243 2019-07-01
3216   Kittitas County   Washington      47935 2019-07-01
3217     Benton County   Washington     204390 2019-07-01
3218      Clark County   Washington     488241 2019-07-01
3219     Warren County    Tennessee      41277 2019-07-01

[3220 rows x 4 columns]

In [31]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2019_county.to_csv("census_2019_county.csv", encoding="utf-8", index=False)

In [32]:
# Run Census Search to retrieve population data
url_2018_county ="https://api.census.gov/data/2018/pep/population?get=GEONAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2018_county)
response_json = response.json()

In [33]:
#Create and rename Dataframe
census_2018_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"County Code"})
census_2018_county["POPULATION"].astype(int)

#string split
census_2018_county[['COUNTY', 'STATE']] = census_2018_county['COUNTY, STATE'].str.split(',', 1, expand=True)
census_2018_county[['DATE', 'Trash']] = census_2018_county['DATE'].str.split(' ', 1, expand=True)

#convert Date to a datetime object
census_2018_county['DATE'] = pd.to_datetime(census_2018_county['DATE'])

#reduced dataframe
census_2018_county = census_2018_county[["COUNTY","STATE","POPULATION","DATE"]]
census_2018_county

                   COUNTY         STATE POPULATION       DATE
0          Autauga County       Alabama      55601 2018-07-01
1          Baldwin County       Alabama     218022 2018-07-01
2          Barbour County       Alabama      24881 2018-07-01
3             Bibb County       Alabama      22400 2018-07-01
4           Blount County       Alabama      57840 2018-07-01
...                   ...           ...        ...        ...
3215  Vega Baja Municipio   Puerto Rico      50185 2018-07-01
3216    Vieques Municipio   Puerto Rico       8364 2018-07-01
3217   Villalba Municipio   Puerto Rico      21476 2018-07-01
3218    Yabucoa Municipio   Puerto Rico      32158 2018-07-01
3219      Yauco Municipio   Puerto Rico      33860 2018-07-01

[3220 rows x 4 columns]

In [34]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2018_county.to_csv("census_2018_county.csv", encoding="utf-8", index=False)

In [35]:
url_2017_county ="https://api.census.gov/data/2017/pep/population?get=GEONAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2017_county)
response_json = response.json()

In [36]:
census_2017_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"County Code"})
census_2017_county["POPULATION"].astype(int)
census_2017_county

#string split
census_2017_county[['COUNTY', 'STATE']] = census_2017_county['COUNTY, STATE'].str.split(',', 1, expand=True)
census_2017_county[['DATE', 'Trash']] = census_2017_county['DATE'].str.split(' ', 1, expand=True)

#convert Date to a datetime object
census_2017_county['DATE'] = pd.to_datetime(census_2017_county['DATE'])

#reduced dataframe
census_2017_county = census_2017_county[["COUNTY","STATE","POPULATION","DATE"]]

census_2017_county

                   COUNTY                      STATE POPULATION       DATE
0          Conecuh County                    Alabama      12469 2017-07-01
1            Coosa County                    Alabama      10754 2017-07-01
2        Covington County                    Alabama      37092 2017-07-01
3         Crenshaw County                    Alabama      13871 2017-07-01
4          Cullman County                    Alabama      82755 2017-07-01
...                   ...                        ...        ...        ...
3215       Moca Municipio   Puerto Rico Commonwealth      36328 2017-07-01
3216    Morovis Municipio   Puerto Rico Commonwealth      31092 2017-07-01
3217    Naguabo Municipio   Puerto Rico Commonwealth      26177 2017-07-01
3218  Naranjito Municipio   Puerto Rico Commonwealth      28306 2017-07-01
3219   Orocovis Municipio   Puerto Rico Commonwealth      21109 2017-07-01

[3220 rows x 4 columns]

In [37]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2017_county.to_csv("census_2017_county.csv", encoding="utf-8", index=False)

In [38]:
url_2016_county ="https://api.census.gov/data/2016/pep/population?get=GEONAME,POP,DATE_DESC&for=county:*&in=state:*&key="+api_key
response = requests.get(url_2016_county)
response_json = response.json()

In [39]:
census_2016_county = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"COUNTY, STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code", "county":"County Code"})
census_2016_county["POPULATION"].astype(int)

#string split
census_2016_county[['COUNTY', 'STATE']] = census_2016_county['COUNTY, STATE'].str.split(',', 1, expand=True)
census_2016_county[['DATE', 'Trash']] = census_2016_county['DATE'].str.split(' ', 1, expand=True)

#convert Date to a datetime object
census_2016_county['DATE'] = pd.to_datetime(census_2016_county['DATE'])

#reduced dataframe
census_2016_county = census_2016_county[["COUNTY","STATE","POPULATION","DATE"]]
census_2016_county

                    COUNTY      STATE POPULATION       DATE
0           Baldwin County    Alabama     208563 2016-07-01
1           Barbour County    Alabama      25965 2016-07-01
2              Bibb County    Alabama      22643 2016-07-01
3            Blount County    Alabama      57704 2016-07-01
4           Bullock County    Alabama      10362 2016-07-01
...                    ...        ...        ...        ...
3215        Patrick County   Virginia      17923 2016-07-01
3216   Pittsylvania County   Virginia      61687 2016-07-01
3217       Powhatan County   Virginia      28443 2016-07-01
3218  Prince Edward County   Virginia      23142 2016-07-01
3219  Prince George County   Virginia      37845 2016-07-01

[3220 rows x 4 columns]

In [40]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2016_county.to_csv("census_2016_county.csv", encoding="utf-8", index=False)