In [10]:
#T.BRADFORD
#July 2021
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json
from census import Census

# Census API Key
from config import api_key

In [11]:
# Run Census Search to retrieve population data
url_2019_state ="https://api.census.gov/data/2019/pep/population?get=NAME,POP,DATE_DESC&for=state:*&key="+api_key
response = requests.get(url_2019_state)
response_json = response.json()

In [12]:
#Create and rename Dataframe
census_2019_state = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"NAME":"STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code"})
census_2019_state["POPULATION"].astype(int)
census_2019_state

                   STATE POPULATION                          DATE State Code
0            Mississippi    2976149  7/1/2019 population estimate         28
1               Missouri    6137428  7/1/2019 population estimate         29
2                Montana    1068778  7/1/2019 population estimate         30
3               Nebraska    1934408  7/1/2019 population estimate         31
4                 Nevada    3080156  7/1/2019 population estimate         32
5          New Hampshire    1359711  7/1/2019 population estimate         33
6             New Jersey    8882190  7/1/2019 population estimate         34
7             New Mexico    2096829  7/1/2019 population estimate         35
8               New York   19453561  7/1/2019 population estimate         36
9         North Carolina   10488084  7/1/2019 population estimate         37
10          North Dakota     762062  7/1/2019 population estimate         38
11                  Ohio   11689100  7/1/2019 population estimate         39
12              Oklahoma    3956971  7/1/2019 population estimate         40
13                Oregon    4217737  7/1/2019 population estimate         41
14          Pennsylvania   12801989  7/1/2019 population estimate         42
15          Rhode Island    1059361  7/1/2019 population estimate         44
16        South Carolina    5148714  7/1/2019 population estimate         45
17          South Dakota     884659  7/1/2019 population estimate         46
18             Tennessee    6829174  7/1/2019 population estimate         47
19                 Texas   28995881  7/1/2019 population estimate         48
20               Vermont     623989  7/1/2019 population estimate         50
21                  Utah    3205958  7/1/2019 population estimate         49
22              Virginia    8535519  7/1/2019 population estimate         51
23            Washington    7614893  7/1/2019 population estimate         53
24         West Virginia    1792147  7/1/2019 population estimate         54
25             Wisconsin    5822434  7/1/2019 population estimate         55
26               Wyoming     578759  7/1/2019 population estimate         56
27           Puerto Rico    3193694  7/1/2019 population estimate         72
28               Alabama    4903185  7/1/2019 population estimate         01
29                Alaska     731545  7/1/2019 population estimate         02
30               Arizona    7278717  7/1/2019 population estimate         04
31              Arkansas    3017804  7/1/2019 population estimate         05
32            California   39512223  7/1/2019 population estimate         06
33              Colorado    5758736  7/1/2019 population estimate         08
34              Delaware     973764  7/1/2019 population estimate         10
35  District of Columbia     705749  7/1/2019 population estimate         11
36           Connecticut    3565287  7/1/2019 population estimate         09
37               Florida   21477737  7/1/2019 population estimate         12
38               Georgia   10617423  7/1/2019 population estimate         13
39                 Idaho    1787065  7/1/2019 population estimate         16
40                Hawaii    1415872  7/1/2019 population estimate         15
41              Illinois   12671821  7/1/2019 population estimate         17
42               Indiana    6732219  7/1/2019 population estimate         18
43                  Iowa    3155070  7/1/2019 population estimate         19
44                Kansas    2913314  7/1/2019 population estimate         20
45              Kentucky    4467673  7/1/2019 population estimate         21
46             Louisiana    4648794  7/1/2019 population estimate         22
47                 Maine    1344212  7/1/2019 population estimate         23
48              Maryland    6045680  7/1/2019 population estimate         24
49         Massachusetts    6892503  7/1/2019 population estimate         25
50              Michigan    9986857  7/1/2019 population estimate         26
51             Minnesota    5639632  7/1/2019 population estimate         27

In [13]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2019_state.to_csv("census_2019_state.csv", encoding="utf-8", index=False)

In [14]:
# Run Census Search to retrieve population data
url_2018_state ="https://api.census.gov/data/2018/pep/population?get=GEONAME,POP,DATE_DESC&for=state:*&key="+api_key
response = requests.get(url_2018_state)
response_json = response.json()

In [15]:
#Create and rename Dataframe
census_2018_state = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code"})
census_2018_state["POPULATION"].astype(int)
census_2018_state

                   STATE POPULATION                          DATE State Code
0                Alabama    4887871  7/1/2018 population estimate         01
1                 Alaska     737438  7/1/2018 population estimate         02
2                Arizona    7171646  7/1/2018 population estimate         04
3               Arkansas    3013825  7/1/2018 population estimate         05
4             California   39557045  7/1/2018 population estimate         06
5               Colorado    5695564  7/1/2018 population estimate         08
6            Connecticut    3572665  7/1/2018 population estimate         09
7               Delaware     967171  7/1/2018 population estimate         10
8   District of Columbia     702455  7/1/2018 population estimate         11
9                Florida   21299325  7/1/2018 population estimate         12
10               Georgia   10519475  7/1/2018 population estimate         13
11                Hawaii    1420491  7/1/2018 population estimate         15
12                 Idaho    1754208  7/1/2018 population estimate         16
13              Illinois   12741080  7/1/2018 population estimate         17
14               Indiana    6691878  7/1/2018 population estimate         18
15                  Iowa    3156145  7/1/2018 population estimate         19
16                Kansas    2911505  7/1/2018 population estimate         20
17              Kentucky    4468402  7/1/2018 population estimate         21
18             Louisiana    4659978  7/1/2018 population estimate         22
19                 Maine    1338404  7/1/2018 population estimate         23
20              Maryland    6042718  7/1/2018 population estimate         24
21         Massachusetts    6902149  7/1/2018 population estimate         25
22              Michigan    9995915  7/1/2018 population estimate         26
23             Minnesota    5611179  7/1/2018 population estimate         27
24           Mississippi    2986530  7/1/2018 population estimate         28
25              Missouri    6126452  7/1/2018 population estimate         29
26               Montana    1062305  7/1/2018 population estimate         30
27              Nebraska    1929268  7/1/2018 population estimate         31
28                Nevada    3034392  7/1/2018 population estimate         32
29         New Hampshire    1356458  7/1/2018 population estimate         33
30            New Jersey    8908520  7/1/2018 population estimate         34
31            New Mexico    2095428  7/1/2018 population estimate         35
32              New York   19542209  7/1/2018 population estimate         36
33        North Carolina   10383620  7/1/2018 population estimate         37
34          North Dakota     760077  7/1/2018 population estimate         38
35                  Ohio   11689442  7/1/2018 population estimate         39
36              Oklahoma    3943079  7/1/2018 population estimate         40
37                Oregon    4190713  7/1/2018 population estimate         41
38          Pennsylvania   12807060  7/1/2018 population estimate         42
39          Rhode Island    1057315  7/1/2018 population estimate         44
40        South Carolina    5084127  7/1/2018 population estimate         45
41          South Dakota     882235  7/1/2018 population estimate         46
42             Tennessee    6770010  7/1/2018 population estimate         47
43                 Texas   28701845  7/1/2018 population estimate         48
44                  Utah    3161105  7/1/2018 population estimate         49
45               Vermont     626299  7/1/2018 population estimate         50
46              Virginia    8517685  7/1/2018 population estimate         51
47            Washington    7535591  7/1/2018 population estimate         53
48         West Virginia    1805832  7/1/2018 population estimate         54
49             Wisconsin    5813568  7/1/2018 population estimate         55
50               Wyoming     577737  7/1/2018 population estimate         56
51           Puerto Rico    3195153  7/1/2018 population estimate         72

In [16]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2018_state.to_csv("census_2018_state.csv", encoding="utf-8", index=False)

In [17]:
# Run Census Search to retrieve population data
url_2017_state ="https://api.census.gov/data/2017/pep/population?get=GEONAME,POP,DATE_DESC&for=state:*&key="+api_key
response = requests.get(url_2017_state)
response_json = response.json()

In [18]:
#Create and rename Dataframe
census_2017_state = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code"})
census_2017_state["POPULATION"].astype(int)
census_2017_state

                   STATE POPULATION                          DATE State Code
0   District of Columbia     693972  7/1/2017 population estimate         11
1                Florida   20984400  7/1/2017 population estimate         12
2                Georgia   10429379  7/1/2017 population estimate         13
3                 Hawaii    1427538  7/1/2017 population estimate         15
4                  Idaho    1716943  7/1/2017 population estimate         16
5               Illinois   12802023  7/1/2017 population estimate         17
6                Indiana    6666818  7/1/2017 population estimate         18
7                   Iowa    3145711  7/1/2017 population estimate         19
8                 Kansas    2913123  7/1/2017 population estimate         20
9               Kentucky    4454189  7/1/2017 population estimate         21
10             Louisiana    4684333  7/1/2017 population estimate         22
11                 Maine    1335907  7/1/2017 population estimate         23
12              Maryland    6052177  7/1/2017 population estimate         24
13         Massachusetts    6859819  7/1/2017 population estimate         25
14               Alabama    4874747  7/1/2017 population estimate         01
15                Alaska     739795  7/1/2017 population estimate         02
16               Arizona    7016270  7/1/2017 population estimate         04
17              Arkansas    3004279  7/1/2017 population estimate         05
18            California   39536653  7/1/2017 population estimate         06
19              Colorado    5607154  7/1/2017 population estimate         08
20           Connecticut    3588184  7/1/2017 population estimate         09
21              Delaware     961939  7/1/2017 population estimate         10
22              Michigan    9962311  7/1/2017 population estimate         26
23             Minnesota    5576606  7/1/2017 population estimate         27
24           Mississippi    2984100  7/1/2017 population estimate         28
25              Missouri    6113532  7/1/2017 population estimate         29
26               Montana    1050493  7/1/2017 population estimate         30
27              Nebraska    1920076  7/1/2017 population estimate         31
28                Nevada    2998039  7/1/2017 population estimate         32
29         New Hampshire    1342795  7/1/2017 population estimate         33
30            New Jersey    9005644  7/1/2017 population estimate         34
31            New Mexico    2088070  7/1/2017 population estimate         35
32              New York   19849399  7/1/2017 population estimate         36
33        North Carolina   10273419  7/1/2017 population estimate         37
34          North Dakota     755393  7/1/2017 population estimate         38
35                  Ohio   11658609  7/1/2017 population estimate         39
36              Oklahoma    3930864  7/1/2017 population estimate         40
37                Oregon    4142776  7/1/2017 population estimate         41
38          Pennsylvania   12805537  7/1/2017 population estimate         42
39          Rhode Island    1059639  7/1/2017 population estimate         44
40        South Carolina    5024369  7/1/2017 population estimate         45
41          South Dakota     869666  7/1/2017 population estimate         46
42             Tennessee    6715984  7/1/2017 population estimate         47
43                 Texas   28304596  7/1/2017 population estimate         48
44                  Utah    3101833  7/1/2017 population estimate         49
45               Vermont     623657  7/1/2017 population estimate         50
46              Virginia    8470020  7/1/2017 population estimate         51
47            Washington    7405743  7/1/2017 population estimate         53
48         West Virginia    1815857  7/1/2017 population estimate         54
49             Wisconsin    5795483  7/1/2017 population estimate         55
50               Wyoming     579315  7/1/2017 population estimate         56
51           Puerto Rico    3337177  7/1/2017 population estimate         72

In [19]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2017_state.to_csv("census_2017_state.csv", encoding="utf-8", index=False)

In [20]:
# Run Census Search to retrieve population data
url_2016_state ="https://api.census.gov/data/2016/pep/population?get=GEONAME,POP,DATE_DESC&for=state:*&key="+api_key
response = requests.get(url_2016_state)
response_json = response.json()

In [21]:
#Create and rename Dataframe
census_2016_state = pd.DataFrame(response.json()[1:], columns=response.json()[0]).rename(columns=
{"GEONAME":"STATE", "POP":"POPULATION","DATE_DESC":"DATE","state":"State Code"})
census_2016_state["POPULATION"].astype(int)
census_2016_state

,STATE,POPULATION,DATE,State Code
0,Alaska,741894,7/1/2016 population_old estimate,02
1,Arizona,6931071,7/1/2016 population_old estimate,04
2,Arkansas,2988248,7/1/2016 population_old estimate,05
3,California,39250017,7/1/2016 population_old estimate,06
4,Colorado,5540545,7/1/2016 population_old estimate,08
5,Connecticut,3576452,7/1/2016 population_old estimate,09
6,Delaware,952065,7/1/2016 population_old estimate,10
7,District of Columbia,681170,7/1/2016 population_old estimate,11
8,Florida,20612439,7/1/2016 population_old estimate,12
9,Georgia,10310371,7/1/2016 population_old estimate,13
10,Hawaii,1428557,7/1/2016 population_old estimate,15
11,Idaho,1683140,7/1/2016 population_old estimate,16
12,Illinois,12801539,7/1/2016 population_old estimate,17
13,Indiana,6633053,7/1/2016 population_old estimate,18
14,Iowa,3134693,7/1/2016 population_old estimate,19
15,Kansas,2907289,7/1/2016 population_old estimate,20
16,Kentucky,4436974,7/1/2016 population_old estimate,21
17,Louisiana,4681666,7/1/2016 population_old estimate,22
18,Maine,1331479,7/1/2016 population_old estimate,23
19,Maryland,6016447,7/1/2016 population_old estimate,24
20,Massachusetts,6811779,7/1/2016 population_old estimate,25
21,Michigan,9928300,7/1/2016 population_old estimate,26
22,Minnesota,5519952,7/1/2016 population_old estimate,27
23,Alabama,4863300,7/1/2016 population_old estimate,01
24,Mississippi,2988726,7/1/2016 population_old estimate,28
25,Missouri,6093000,7/1/2016 population_old estimate,29
26,Montana,1042520,7/1/2016 population_old estimate,30
27,Nebraska,1907116,7/1/2016 population_old estimate,31
28,Nevada,2940058,7/1/2016 population_old estimate,32
29,New Hampshire,1334795,7/1/2016 population_old estimate,33
30,New Jersey,8944469,7/1/2016 population_old estimate,34
31,New Mexico,2081015,7/1/2016 population_old estimate,35
32,New York,19745289,7/1/2016 population_old estimate,36
33,North Carolina,10146788,7/1/2016 population_old estimate,37
34,North Dakota,757952,7/1/2016 population_old estimate,38
35,Ohio,11614373,7/1/2016 population_old estimate,39
36,Oklahoma,3923561,7/1/2016 population_old estimate,40
37,Oregon,4093465,7/1/2016 population_old estimate,41
38,Pennsylvania,12784227,7/1/2016 population_old estimate,42
39,Rhode Island,1056426,7/1/2016 population_old estimate,44
40,South Carolina,4961119,7/1/2016 population_old estimate,45
41,South Dakota,865454,7/1/2016 population_old estimate,46
42,Tennessee,6651194,7/1/2016 population_old estimate,47
43,Texas,27862596,7/1/2016 population_old estimate,48
44,Utah,3051217,7/1/2016 population_old estimate,49
45,Vermont,624594,7/1/2016 population_old estimate,50
46,Virginia,8411808,7/1/2016 population_old estimate,51
47,Washington,7288000,7/1/2016 population_old estimate,53
48,West Virginia,1831102,7/1/2016 population_old estimate,54
49,Wisconsin,5778708,7/1/2016 population_old estimate,55
50,Wyoming,585501,7/1/2016 population_old estimate,56
51,Puerto Rico,3411307,7/1/2016 population_old estimate,72

In [22]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_2016_state.to_csv("census_2016_state.csv", encoding="utf-8", index=False)